# This is used by Github actions to ensure docker images build properly.
version: "3.9"

services:
  ihatemoney:
    build: .
  sut:
    image: alpine
    command: sh -c 'wget -qO- ihatemoney:8000/healthcheck | grep "OK"'
    depends_on:
      - ihatemoney
